# Generated by Django 4.0.6 on 2024-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_author_desc_category_img_alter_category_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='post-img'),
        ),
    ]
