# Generated by Django 4.0.6 on 2024-10-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_body1_post_body2_post_body3_post_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section3',
        ),
    ]
