# Generated by Django 4.0.6 on 2024-10-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_post_body1_remove_post_body2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
    ]
